### ISSUE TITLE
Westcrest

### ISSUE THREAD

**Issue by kpetersmark** [thewellington/whereisourplayground.org#1]
Wasn't sure how to fork a branch for another playground that has seen long delays, but Westcrest has been without a playrground for 2+ years. If you want to add that one as well.

Timeline
January 2021 - Westcrest playground is fenced off after a structural survey deemed repairs were beyond minor replacements and the 19 year old structure was one year away from it's 20-year life. 
January 2021 - Karen O'Connor states "We understand that closure of the structure is disappointing, and we are planning on a short replacement timeline."
February 2022 - Oliver Bazinet states "Basically, we are no longer able to use a more streamlined purchasing mechanism that we previously used for installation of play equipment at this scale. We’ve adjusted to a strategy of including this work as part of a larger bid package.  A new (to this project) project manager has been assigned and I have requested that they keep you up to date when they have a more firm timeline."
March 2022 - Website updated to indicate bids will go out in Summer of 2022 with installation to complete in Fall of 2022.
August 2022 - No bids went out. Karen O'Connor says "We anticipate the project going out to bid in the fall.  We have bundled this project with the Lincoln Park South Play Area."
December 2022 - Shannon Glass announces more delays "The bid for construction will be advertised in January or February 2023".

No response from emails in March 2023 asking for an update.

**Comment by thewellington** [comment]
Beautiful!  I just spent today working on pages for Hiawatha.   I will get these in for Westcrest in the next couple of days.

Thanks Much for detailing this park.

**Comment by thewellington** [comment]
Westcrest Details posted.   Will try to get out tomorrow to get photos of the play area

**Comment by thewellington** [comment]
resolved in #916dac04
